/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CentralRouteImport } from './routes/central'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as HooksRefreshTrackingRouteImport } from './routes/hooks/refresh-tracking'
import { Route as ConfiguracoesZapiRouteImport } from './routes/configuracoes.zapi'
import { Route as ConfiguracoesUsuariosRouteImport } from './routes/configuracoes.usuarios'
import { Route as ConfiguracoesFluxoAtendimentoRouteImport } from './routes/configuracoes.fluxo-atendimento'
import { Route as ConfiguracoesEstoqueRouteImport } from './routes/configuracoes.estoque'
import { Route as ConfiguracoesEncaminhamentoRouteImport } from './routes/configuracoes.encaminhamento'
import { Route as ConfiguracoesCentralAtendimentoRouteImport } from './routes/configuracoes.central-atendimento'
import { Route as ConfiguracoesAssistenteIaRouteImport } from './routes/configuracoes.assistente-ia'
import { Route as AtendimentosTarefasRouteImport } from './routes/atendimentos.tarefas'
import { Route as ApiPublicZapiWebhookChannelIdRouteImport } from './routes/api.public.zapi-webhook.$channelId'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const HooksRefreshTrackingRoute = HooksRefreshTrackingRouteImport.update({
  id: '/hooks/refresh-tracking',
  path: '/hooks/refresh-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesZapiRoute = ConfiguracoesZapiRouteImport.update({
  id: '/zapi',
  path: '/zapi',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesUsuariosRoute = ConfiguracoesUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesFluxoAtendimentoRoute =
  ConfiguracoesFluxoAtendimentoRouteImport.update({
    id: '/fluxo-atendimento',
    path: '/fluxo-atendimento',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesEstoqueRoute = ConfiguracoesEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesEncaminhamentoRoute =
  ConfiguracoesEncaminhamentoRouteImport.update({
    id: '/encaminhamento',
    path: '/encaminhamento',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesCentralAtendimentoRoute =
  ConfiguracoesCentralAtendimentoRouteImport.update({
    id: '/central-atendimento',
    path: '/central-atendimento',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesAssistenteIaRoute =
  ConfiguracoesAssistenteIaRouteImport.update({
    id: '/assistente-ia',
    path: '/assistente-ia',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const AtendimentosTarefasRoute = AtendimentosTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AtendimentosRoute,
} as any)
const ApiPublicZapiWebhookChannelIdRoute =
  ApiPublicZapiWebhookChannelIdRouteImport.update({
    id: '/api/public/zapi-webhook/$channelId',
    path: '/api/public/zapi-webhook/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/central': typeof CentralRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/relatorios': typeof RelatoriosRoute
  '/atendimentos/tarefas': typeof AtendimentosTarefasRoute
  '/configuracoes/assistente-ia': typeof ConfiguracoesAssistenteIaRoute
  '/configuracoes/central-atendimento': typeof ConfiguracoesCentralAtendimentoRoute
  '/configuracoes/encaminhamento': typeof ConfiguracoesEncaminhamentoRoute
  '/configuracoes/estoque': typeof ConfiguracoesEstoqueRoute
  '/configuracoes/fluxo-atendimento': typeof ConfiguracoesFluxoAtendimentoRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/configuracoes/zapi': typeof ConfiguracoesZapiRoute
  '/hooks/refresh-tracking': typeof HooksRefreshTrackingRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/api/public/zapi-webhook/$channelId': typeof ApiPublicZapiWebhookChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/central': typeof CentralRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/relatorios': typeof RelatoriosRoute
  '/atendimentos/tarefas': typeof AtendimentosTarefasRoute
  '/configuracoes/assistente-ia': typeof ConfiguracoesAssistenteIaRoute
  '/configuracoes/central-atendimento': typeof ConfiguracoesCentralAtendimentoRoute
  '/configuracoes/encaminhamento': typeof ConfiguracoesEncaminhamentoRoute
  '/configuracoes/estoque': typeof ConfiguracoesEstoqueRoute
  '/configuracoes/fluxo-atendimento': typeof ConfiguracoesFluxoAtendimentoRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/configuracoes/zapi': typeof ConfiguracoesZapiRoute
  '/hooks/refresh-tracking': typeof HooksRefreshTrackingRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/api/public/zapi-webhook/$channelId': typeof ApiPublicZapiWebhookChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/central': typeof CentralRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/relatorios': typeof RelatoriosRoute
  '/atendimentos/tarefas': typeof AtendimentosTarefasRoute
  '/configuracoes/assistente-ia': typeof ConfiguracoesAssistenteIaRoute
  '/configuracoes/central-atendimento': typeof ConfiguracoesCentralAtendimentoRoute
  '/configuracoes/encaminhamento': typeof ConfiguracoesEncaminhamentoRoute
  '/configuracoes/estoque': typeof ConfiguracoesEstoqueRoute
  '/configuracoes/fluxo-atendimento': typeof ConfiguracoesFluxoAtendimentoRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/configuracoes/zapi': typeof ConfiguracoesZapiRoute
  '/hooks/refresh-tracking': typeof HooksRefreshTrackingRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/api/public/zapi-webhook/$channelId': typeof ApiPublicZapiWebhookChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimentos'
    | '/central'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/empresas'
    | '/estoque'
    | '/relatorios'
    | '/atendimentos/tarefas'
    | '/configuracoes/assistente-ia'
    | '/configuracoes/central-atendimento'
    | '/configuracoes/encaminhamento'
    | '/configuracoes/estoque'
    | '/configuracoes/fluxo-atendimento'
    | '/configuracoes/usuarios'
    | '/configuracoes/zapi'
    | '/hooks/refresh-tracking'
    | '/configuracoes/'
    | '/api/public/zapi-webhook/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimentos'
    | '/central'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/empresas'
    | '/estoque'
    | '/relatorios'
    | '/atendimentos/tarefas'
    | '/configuracoes/assistente-ia'
    | '/configuracoes/central-atendimento'
    | '/configuracoes/encaminhamento'
    | '/configuracoes/estoque'
    | '/configuracoes/fluxo-atendimento'
    | '/configuracoes/usuarios'
    | '/configuracoes/zapi'
    | '/hooks/refresh-tracking'
    | '/configuracoes'
    | '/api/public/zapi-webhook/$channelId'
  id:
    | '__root__'
    | '/'
    | '/atendimentos'
    | '/central'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/empresas'
    | '/estoque'
    | '/relatorios'
    | '/atendimentos/tarefas'
    | '/configuracoes/assistente-ia'
    | '/configuracoes/central-atendimento'
    | '/configuracoes/encaminhamento'
    | '/configuracoes/estoque'
    | '/configuracoes/fluxo-atendimento'
    | '/configuracoes/usuarios'
    | '/configuracoes/zapi'
    | '/hooks/refresh-tracking'
    | '/configuracoes/'
    | '/api/public/zapi-webhook/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentosRoute: typeof AtendimentosRouteWithChildren
  CentralRoute: typeof CentralRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ContatosRoute: typeof ContatosRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  EmpresasRoute: typeof EmpresasRoute
  EstoqueRoute: typeof EstoqueRoute
  RelatoriosRoute: typeof RelatoriosRoute
  HooksRefreshTrackingRoute: typeof HooksRefreshTrackingRoute
  ApiPublicZapiWebhookChannelIdRoute: typeof ApiPublicZapiWebhookChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/hooks/refresh-tracking': {
      id: '/hooks/refresh-tracking'
      path: '/hooks/refresh-tracking'
      fullPath: '/hooks/refresh-tracking'
      preLoaderRoute: typeof HooksRefreshTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/zapi': {
      id: '/configuracoes/zapi'
      path: '/zapi'
      fullPath: '/configuracoes/zapi'
      preLoaderRoute: typeof ConfiguracoesZapiRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/usuarios': {
      id: '/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof ConfiguracoesUsuariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/fluxo-atendimento': {
      id: '/configuracoes/fluxo-atendimento'
      path: '/fluxo-atendimento'
      fullPath: '/configuracoes/fluxo-atendimento'
      preLoaderRoute: typeof ConfiguracoesFluxoAtendimentoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/estoque': {
      id: '/configuracoes/estoque'
      path: '/estoque'
      fullPath: '/configuracoes/estoque'
      preLoaderRoute: typeof ConfiguracoesEstoqueRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/encaminhamento': {
      id: '/configuracoes/encaminhamento'
      path: '/encaminhamento'
      fullPath: '/configuracoes/encaminhamento'
      preLoaderRoute: typeof ConfiguracoesEncaminhamentoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/central-atendimento': {
      id: '/configuracoes/central-atendimento'
      path: '/central-atendimento'
      fullPath: '/configuracoes/central-atendimento'
      preLoaderRoute: typeof ConfiguracoesCentralAtendimentoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/assistente-ia': {
      id: '/configuracoes/assistente-ia'
      path: '/assistente-ia'
      fullPath: '/configuracoes/assistente-ia'
      preLoaderRoute: typeof ConfiguracoesAssistenteIaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/atendimentos/tarefas': {
      id: '/atendimentos/tarefas'
      path: '/tarefas'
      fullPath: '/atendimentos/tarefas'
      preLoaderRoute: typeof AtendimentosTarefasRouteImport
      parentRoute: typeof AtendimentosRoute
    }
    '/api/public/zapi-webhook/$channelId': {
      id: '/api/public/zapi-webhook/$channelId'
      path: '/api/public/zapi-webhook/$channelId'
      fullPath: '/api/public/zapi-webhook/$channelId'
      preLoaderRoute: typeof ApiPublicZapiWebhookChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AtendimentosRouteChildren {
  AtendimentosTarefasRoute: typeof AtendimentosTarefasRoute
}

const AtendimentosRouteChildren: AtendimentosRouteChildren = {
  AtendimentosTarefasRoute: AtendimentosTarefasRoute,
}

const AtendimentosRouteWithChildren = AtendimentosRoute._addFileChildren(
  AtendimentosRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesAssistenteIaRoute: typeof ConfiguracoesAssistenteIaRoute
  ConfiguracoesCentralAtendimentoRoute: typeof ConfiguracoesCentralAtendimentoRoute
  ConfiguracoesEncaminhamentoRoute: typeof ConfiguracoesEncaminhamentoRoute
  ConfiguracoesEstoqueRoute: typeof ConfiguracoesEstoqueRoute
  ConfiguracoesFluxoAtendimentoRoute: typeof ConfiguracoesFluxoAtendimentoRoute
  ConfiguracoesUsuariosRoute: typeof ConfiguracoesUsuariosRoute
  ConfiguracoesZapiRoute: typeof ConfiguracoesZapiRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesAssistenteIaRoute: ConfiguracoesAssistenteIaRoute,
  ConfiguracoesCentralAtendimentoRoute: ConfiguracoesCentralAtendimentoRoute,
  ConfiguracoesEncaminhamentoRoute: ConfiguracoesEncaminhamentoRoute,
  ConfiguracoesEstoqueRoute: ConfiguracoesEstoqueRoute,
  ConfiguracoesFluxoAtendimentoRoute: ConfiguracoesFluxoAtendimentoRoute,
  ConfiguracoesUsuariosRoute: ConfiguracoesUsuariosRoute,
  ConfiguracoesZapiRoute: ConfiguracoesZapiRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentosRoute: AtendimentosRouteWithChildren,
  CentralRoute: CentralRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ContatosRoute: ContatosRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  EmpresasRoute: EmpresasRoute,
  EstoqueRoute: EstoqueRoute,
  RelatoriosRoute: RelatoriosRoute,
  HooksRefreshTrackingRoute: HooksRefreshTrackingRoute,
  ApiPublicZapiWebhookChannelIdRoute: ApiPublicZapiWebhookChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
