/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratativasRouteImport } from './routes/tratativas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PainelTvRouteImport } from './routes/painel-tv'
import { Route as OkrRouteImport } from './routes/okr'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatOperadoresRouteImport } from './routes/chat-operadores'
import { Route as CentralRouteImport } from './routes/central'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as HooksRefreshTrackingRouteImport } from './routes/hooks/refresh-tracking'
import { Route as ConfiguracoesZapiRouteImport } from './routes/configuracoes.zapi'
import { Route as ConfiguracoesUsuariosRouteImport } from './routes/configuracoes.usuarios'
import { Route as ConfiguracoesStatusUsuariosRouteImport } from './routes/configuracoes.status-usuarios'
import { Route as ConfiguracoesPopupDiarioRouteImport } from './routes/configuracoes.popup-diario'
import { Route as ConfiguracoesOkrRouteImport } from './routes/configuracoes.okr'
import { Route as ConfiguracoesNotificacoesRouteImport } from './routes/configuracoes.notificacoes'
import { Route as ConfiguracoesFluxoAtendimentoRouteImport } from './routes/configuracoes.fluxo-atendimento'
import { Route as ConfiguracoesEstoqueRouteImport } from './routes/configuracoes.estoque'
import { Route as ConfiguracoesEncaminhamentoRouteImport } from './routes/configuracoes.encaminhamento'
import { Route as ConfiguracoesCentralAtendimentoRouteImport } from './routes/configuracoes.central-atendimento'
import { Route as ConfiguracoesAutomacaoSemComunicacaoRouteImport } from './routes/configuracoes.automacao-sem-comunicacao'
import { Route as ConfiguracoesAuditoriaRouteImport } from './routes/configuracoes.auditoria'
import { Route as ConfiguracoesAssistenteIaRouteImport } from './routes/configuracoes.assistente-ia'
import { Route as AtendimentosTarefasRouteImport } from './routes/atendimentos_.tarefas'
import { Route as ApiPublicEmailPollRouteImport } from './routes/api.public.email-poll'
import { Route as ApiPublicCrmDailyRouteImport } from './routes/api.public.crm-daily'
import { Route as ApiPublicChatIdleScannerRouteImport } from './routes/api.public.chat-idle-scanner'
import { Route as ApiPublicAutoRouteAguardandoRouteImport } from './routes/api.public.auto-route-aguardando'
import { Route as ApiPublicZapiWebhookChannelIdRouteImport } from './routes/api.public.zapi-webhook.$channelId'

const TratativasRoute = TratativasRouteImport.update({
  id: '/tratativas',
  path: '/tratativas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelTvRoute = PainelTvRouteImport.update({
  id: '/painel-tv',
  path: '/painel-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const OkrRoute = OkrRouteImport.update({
  id: '/okr',
  path: '/okr',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOperadoresRoute = ChatOperadoresRouteImport.update({
  id: '/chat-operadores',
  path: '/chat-operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const HooksRefreshTrackingRoute = HooksRefreshTrackingRouteImport.update({
  id: '/hooks/refresh-tracking',
  path: '/hooks/refresh-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesZapiRoute = ConfiguracoesZapiRouteImport.update({
  id: '/zapi',
  path: '/zapi',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesUsuariosRoute = ConfiguracoesUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesStatusUsuariosRoute =
  ConfiguracoesStatusUsuariosRouteImport.update({
    id: '/status-usuarios',
    path: '/status-usuarios',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesPopupDiarioRoute =
  ConfiguracoesPopupDiarioRouteImport.update({
    id: '/popup-diario',
    path: '/popup-diario',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesOkrRoute = ConfiguracoesOkrRouteImport.update({
  id: '/okr',
  path: '/okr',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesNotificacoesRoute =
  ConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesFluxoAtendimentoRoute =
  ConfiguracoesFluxoAtendimentoRouteImport.update({
    id: '/fluxo-atendimento',
    path: '/fluxo-atendimento',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesEstoqueRoute = ConfiguracoesEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesEncaminhamentoRoute =
  ConfiguracoesEncaminhamentoRouteImport.update({
    id: '/encaminhamento',
    path: '/encaminhamento',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesCentralAtendimentoRoute =
  ConfiguracoesCentralAtendimentoRouteImport.update({
    id: '/central-atendimento',
    path: '/central-atendimento',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesAutomacaoSemComunicacaoRoute =
  ConfiguracoesAutomacaoSemComunicacaoRouteImport.update({
    id: '/automacao-sem-comunicacao',
    path: '/automacao-sem-comunicacao',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesAuditoriaRoute = ConfiguracoesAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesAssistenteIaRoute =
  ConfiguracoesAssistenteIaRouteImport.update({
    id: '/assistente-ia',
    path: '/assistente-ia',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const AtendimentosTarefasRoute = AtendimentosTarefasRouteImport.update({
  id: '/atendimentos_/tarefas',
  path: '/atendimentos/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailPollRoute = ApiPublicEmailPollRouteImport.update({
  id: '/api/public/email-poll',
  path: '/api/public/email-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmDailyRoute = ApiPublicCrmDailyRouteImport.update({
  id: '/api/public/crm-daily',
  path: '/api/public/crm-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatIdleScannerRoute =
  ApiPublicChatIdleScannerRouteImport.update({
    id: '/api/public/chat-idle-scanner',
    path: '/api/public/chat-idle-scanner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutoRouteAguardandoRoute =
  ApiPublicAutoRouteAguardandoRouteImport.update({
    id: '/api/public/auto-route-aguardando',
    path: '/api/public/auto-route-aguardando',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZapiWebhookChannelIdRoute =
  ApiPublicZapiWebhookChannelIdRouteImport.update({
    id: '/api/public/zapi-webhook/$channelId',
    path: '/api/public/zapi-webhook/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/central': typeof CentralRoute
  '/chat-operadores': typeof ChatOperadoresRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/okr': typeof OkrRoute
  '/painel-tv': typeof PainelTvRoute
  '/relatorios': typeof RelatoriosRoute
  '/tratativas': typeof TratativasRoute
  '/atendimentos/tarefas': typeof AtendimentosTarefasRoute
  '/configuracoes/assistente-ia': typeof ConfiguracoesAssistenteIaRoute
  '/configuracoes/auditoria': typeof ConfiguracoesAuditoriaRoute
  '/configuracoes/automacao-sem-comunicacao': typeof ConfiguracoesAutomacaoSemComunicacaoRoute
  '/configuracoes/central-atendimento': typeof ConfiguracoesCentralAtendimentoRoute
  '/configuracoes/encaminhamento': typeof ConfiguracoesEncaminhamentoRoute
  '/configuracoes/estoque': typeof ConfiguracoesEstoqueRoute
  '/configuracoes/fluxo-atendimento': typeof ConfiguracoesFluxoAtendimentoRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/okr': typeof ConfiguracoesOkrRoute
  '/configuracoes/popup-diario': typeof ConfiguracoesPopupDiarioRoute
  '/configuracoes/status-usuarios': typeof ConfiguracoesStatusUsuariosRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/configuracoes/zapi': typeof ConfiguracoesZapiRoute
  '/hooks/refresh-tracking': typeof HooksRefreshTrackingRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/api/public/auto-route-aguardando': typeof ApiPublicAutoRouteAguardandoRoute
  '/api/public/chat-idle-scanner': typeof ApiPublicChatIdleScannerRoute
  '/api/public/crm-daily': typeof ApiPublicCrmDailyRoute
  '/api/public/email-poll': typeof ApiPublicEmailPollRoute
  '/api/public/zapi-webhook/$channelId': typeof ApiPublicZapiWebhookChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/central': typeof CentralRoute
  '/chat-operadores': typeof ChatOperadoresRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/okr': typeof OkrRoute
  '/painel-tv': typeof PainelTvRoute
  '/relatorios': typeof RelatoriosRoute
  '/tratativas': typeof TratativasRoute
  '/atendimentos/tarefas': typeof AtendimentosTarefasRoute
  '/configuracoes/assistente-ia': typeof ConfiguracoesAssistenteIaRoute
  '/configuracoes/auditoria': typeof ConfiguracoesAuditoriaRoute
  '/configuracoes/automacao-sem-comunicacao': typeof ConfiguracoesAutomacaoSemComunicacaoRoute
  '/configuracoes/central-atendimento': typeof ConfiguracoesCentralAtendimentoRoute
  '/configuracoes/encaminhamento': typeof ConfiguracoesEncaminhamentoRoute
  '/configuracoes/estoque': typeof ConfiguracoesEstoqueRoute
  '/configuracoes/fluxo-atendimento': typeof ConfiguracoesFluxoAtendimentoRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/okr': typeof ConfiguracoesOkrRoute
  '/configuracoes/popup-diario': typeof ConfiguracoesPopupDiarioRoute
  '/configuracoes/status-usuarios': typeof ConfiguracoesStatusUsuariosRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/configuracoes/zapi': typeof ConfiguracoesZapiRoute
  '/hooks/refresh-tracking': typeof HooksRefreshTrackingRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/api/public/auto-route-aguardando': typeof ApiPublicAutoRouteAguardandoRoute
  '/api/public/chat-idle-scanner': typeof ApiPublicChatIdleScannerRoute
  '/api/public/crm-daily': typeof ApiPublicCrmDailyRoute
  '/api/public/email-poll': typeof ApiPublicEmailPollRoute
  '/api/public/zapi-webhook/$channelId': typeof ApiPublicZapiWebhookChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/central': typeof CentralRoute
  '/chat-operadores': typeof ChatOperadoresRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/okr': typeof OkrRoute
  '/painel-tv': typeof PainelTvRoute
  '/relatorios': typeof RelatoriosRoute
  '/tratativas': typeof TratativasRoute
  '/atendimentos_/tarefas': typeof AtendimentosTarefasRoute
  '/configuracoes/assistente-ia': typeof ConfiguracoesAssistenteIaRoute
  '/configuracoes/auditoria': typeof ConfiguracoesAuditoriaRoute
  '/configuracoes/automacao-sem-comunicacao': typeof ConfiguracoesAutomacaoSemComunicacaoRoute
  '/configuracoes/central-atendimento': typeof ConfiguracoesCentralAtendimentoRoute
  '/configuracoes/encaminhamento': typeof ConfiguracoesEncaminhamentoRoute
  '/configuracoes/estoque': typeof ConfiguracoesEstoqueRoute
  '/configuracoes/fluxo-atendimento': typeof ConfiguracoesFluxoAtendimentoRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/okr': typeof ConfiguracoesOkrRoute
  '/configuracoes/popup-diario': typeof ConfiguracoesPopupDiarioRoute
  '/configuracoes/status-usuarios': typeof ConfiguracoesStatusUsuariosRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/configuracoes/zapi': typeof ConfiguracoesZapiRoute
  '/hooks/refresh-tracking': typeof HooksRefreshTrackingRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/api/public/auto-route-aguardando': typeof ApiPublicAutoRouteAguardandoRoute
  '/api/public/chat-idle-scanner': typeof ApiPublicChatIdleScannerRoute
  '/api/public/crm-daily': typeof ApiPublicCrmDailyRoute
  '/api/public/email-poll': typeof ApiPublicEmailPollRoute
  '/api/public/zapi-webhook/$channelId': typeof ApiPublicZapiWebhookChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimentos'
    | '/central'
    | '/chat-operadores'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/empresas'
    | '/estoque'
    | '/okr'
    | '/painel-tv'
    | '/relatorios'
    | '/tratativas'
    | '/atendimentos/tarefas'
    | '/configuracoes/assistente-ia'
    | '/configuracoes/auditoria'
    | '/configuracoes/automacao-sem-comunicacao'
    | '/configuracoes/central-atendimento'
    | '/configuracoes/encaminhamento'
    | '/configuracoes/estoque'
    | '/configuracoes/fluxo-atendimento'
    | '/configuracoes/notificacoes'
    | '/configuracoes/okr'
    | '/configuracoes/popup-diario'
    | '/configuracoes/status-usuarios'
    | '/configuracoes/usuarios'
    | '/configuracoes/zapi'
    | '/hooks/refresh-tracking'
    | '/configuracoes/'
    | '/api/public/auto-route-aguardando'
    | '/api/public/chat-idle-scanner'
    | '/api/public/crm-daily'
    | '/api/public/email-poll'
    | '/api/public/zapi-webhook/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimentos'
    | '/central'
    | '/chat-operadores'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/empresas'
    | '/estoque'
    | '/okr'
    | '/painel-tv'
    | '/relatorios'
    | '/tratativas'
    | '/atendimentos/tarefas'
    | '/configuracoes/assistente-ia'
    | '/configuracoes/auditoria'
    | '/configuracoes/automacao-sem-comunicacao'
    | '/configuracoes/central-atendimento'
    | '/configuracoes/encaminhamento'
    | '/configuracoes/estoque'
    | '/configuracoes/fluxo-atendimento'
    | '/configuracoes/notificacoes'
    | '/configuracoes/okr'
    | '/configuracoes/popup-diario'
    | '/configuracoes/status-usuarios'
    | '/configuracoes/usuarios'
    | '/configuracoes/zapi'
    | '/hooks/refresh-tracking'
    | '/configuracoes'
    | '/api/public/auto-route-aguardando'
    | '/api/public/chat-idle-scanner'
    | '/api/public/crm-daily'
    | '/api/public/email-poll'
    | '/api/public/zapi-webhook/$channelId'
  id:
    | '__root__'
    | '/'
    | '/atendimentos'
    | '/central'
    | '/chat-operadores'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/empresas'
    | '/estoque'
    | '/okr'
    | '/painel-tv'
    | '/relatorios'
    | '/tratativas'
    | '/atendimentos_/tarefas'
    | '/configuracoes/assistente-ia'
    | '/configuracoes/auditoria'
    | '/configuracoes/automacao-sem-comunicacao'
    | '/configuracoes/central-atendimento'
    | '/configuracoes/encaminhamento'
    | '/configuracoes/estoque'
    | '/configuracoes/fluxo-atendimento'
    | '/configuracoes/notificacoes'
    | '/configuracoes/okr'
    | '/configuracoes/popup-diario'
    | '/configuracoes/status-usuarios'
    | '/configuracoes/usuarios'
    | '/configuracoes/zapi'
    | '/hooks/refresh-tracking'
    | '/configuracoes/'
    | '/api/public/auto-route-aguardando'
    | '/api/public/chat-idle-scanner'
    | '/api/public/crm-daily'
    | '/api/public/email-poll'
    | '/api/public/zapi-webhook/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentosRoute: typeof AtendimentosRoute
  CentralRoute: typeof CentralRoute
  ChatOperadoresRoute: typeof ChatOperadoresRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ContatosRoute: typeof ContatosRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  EmpresasRoute: typeof EmpresasRoute
  EstoqueRoute: typeof EstoqueRoute
  OkrRoute: typeof OkrRoute
  PainelTvRoute: typeof PainelTvRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TratativasRoute: typeof TratativasRoute
  AtendimentosTarefasRoute: typeof AtendimentosTarefasRoute
  HooksRefreshTrackingRoute: typeof HooksRefreshTrackingRoute
  ApiPublicAutoRouteAguardandoRoute: typeof ApiPublicAutoRouteAguardandoRoute
  ApiPublicChatIdleScannerRoute: typeof ApiPublicChatIdleScannerRoute
  ApiPublicCrmDailyRoute: typeof ApiPublicCrmDailyRoute
  ApiPublicEmailPollRoute: typeof ApiPublicEmailPollRoute
  ApiPublicZapiWebhookChannelIdRoute: typeof ApiPublicZapiWebhookChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratativas': {
      id: '/tratativas'
      path: '/tratativas'
      fullPath: '/tratativas'
      preLoaderRoute: typeof TratativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-tv': {
      id: '/painel-tv'
      path: '/painel-tv'
      fullPath: '/painel-tv'
      preLoaderRoute: typeof PainelTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okr': {
      id: '/okr'
      path: '/okr'
      fullPath: '/okr'
      preLoaderRoute: typeof OkrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-operadores': {
      id: '/chat-operadores'
      path: '/chat-operadores'
      fullPath: '/chat-operadores'
      preLoaderRoute: typeof ChatOperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/hooks/refresh-tracking': {
      id: '/hooks/refresh-tracking'
      path: '/hooks/refresh-tracking'
      fullPath: '/hooks/refresh-tracking'
      preLoaderRoute: typeof HooksRefreshTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/zapi': {
      id: '/configuracoes/zapi'
      path: '/zapi'
      fullPath: '/configuracoes/zapi'
      preLoaderRoute: typeof ConfiguracoesZapiRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/usuarios': {
      id: '/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof ConfiguracoesUsuariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/status-usuarios': {
      id: '/configuracoes/status-usuarios'
      path: '/status-usuarios'
      fullPath: '/configuracoes/status-usuarios'
      preLoaderRoute: typeof ConfiguracoesStatusUsuariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/popup-diario': {
      id: '/configuracoes/popup-diario'
      path: '/popup-diario'
      fullPath: '/configuracoes/popup-diario'
      preLoaderRoute: typeof ConfiguracoesPopupDiarioRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/okr': {
      id: '/configuracoes/okr'
      path: '/okr'
      fullPath: '/configuracoes/okr'
      preLoaderRoute: typeof ConfiguracoesOkrRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/notificacoes': {
      id: '/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof ConfiguracoesNotificacoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/fluxo-atendimento': {
      id: '/configuracoes/fluxo-atendimento'
      path: '/fluxo-atendimento'
      fullPath: '/configuracoes/fluxo-atendimento'
      preLoaderRoute: typeof ConfiguracoesFluxoAtendimentoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/estoque': {
      id: '/configuracoes/estoque'
      path: '/estoque'
      fullPath: '/configuracoes/estoque'
      preLoaderRoute: typeof ConfiguracoesEstoqueRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/encaminhamento': {
      id: '/configuracoes/encaminhamento'
      path: '/encaminhamento'
      fullPath: '/configuracoes/encaminhamento'
      preLoaderRoute: typeof ConfiguracoesEncaminhamentoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/central-atendimento': {
      id: '/configuracoes/central-atendimento'
      path: '/central-atendimento'
      fullPath: '/configuracoes/central-atendimento'
      preLoaderRoute: typeof ConfiguracoesCentralAtendimentoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/automacao-sem-comunicacao': {
      id: '/configuracoes/automacao-sem-comunicacao'
      path: '/automacao-sem-comunicacao'
      fullPath: '/configuracoes/automacao-sem-comunicacao'
      preLoaderRoute: typeof ConfiguracoesAutomacaoSemComunicacaoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/auditoria': {
      id: '/configuracoes/auditoria'
      path: '/auditoria'
      fullPath: '/configuracoes/auditoria'
      preLoaderRoute: typeof ConfiguracoesAuditoriaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/assistente-ia': {
      id: '/configuracoes/assistente-ia'
      path: '/assistente-ia'
      fullPath: '/configuracoes/assistente-ia'
      preLoaderRoute: typeof ConfiguracoesAssistenteIaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/atendimentos_/tarefas': {
      id: '/atendimentos_/tarefas'
      path: '/atendimentos/tarefas'
      fullPath: '/atendimentos/tarefas'
      preLoaderRoute: typeof AtendimentosTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-poll': {
      id: '/api/public/email-poll'
      path: '/api/public/email-poll'
      fullPath: '/api/public/email-poll'
      preLoaderRoute: typeof ApiPublicEmailPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm-daily': {
      id: '/api/public/crm-daily'
      path: '/api/public/crm-daily'
      fullPath: '/api/public/crm-daily'
      preLoaderRoute: typeof ApiPublicCrmDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-idle-scanner': {
      id: '/api/public/chat-idle-scanner'
      path: '/api/public/chat-idle-scanner'
      fullPath: '/api/public/chat-idle-scanner'
      preLoaderRoute: typeof ApiPublicChatIdleScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auto-route-aguardando': {
      id: '/api/public/auto-route-aguardando'
      path: '/api/public/auto-route-aguardando'
      fullPath: '/api/public/auto-route-aguardando'
      preLoaderRoute: typeof ApiPublicAutoRouteAguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapi-webhook/$channelId': {
      id: '/api/public/zapi-webhook/$channelId'
      path: '/api/public/zapi-webhook/$channelId'
      fullPath: '/api/public/zapi-webhook/$channelId'
      preLoaderRoute: typeof ApiPublicZapiWebhookChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesAssistenteIaRoute: typeof ConfiguracoesAssistenteIaRoute
  ConfiguracoesAuditoriaRoute: typeof ConfiguracoesAuditoriaRoute
  ConfiguracoesAutomacaoSemComunicacaoRoute: typeof ConfiguracoesAutomacaoSemComunicacaoRoute
  ConfiguracoesCentralAtendimentoRoute: typeof ConfiguracoesCentralAtendimentoRoute
  ConfiguracoesEncaminhamentoRoute: typeof ConfiguracoesEncaminhamentoRoute
  ConfiguracoesEstoqueRoute: typeof ConfiguracoesEstoqueRoute
  ConfiguracoesFluxoAtendimentoRoute: typeof ConfiguracoesFluxoAtendimentoRoute
  ConfiguracoesNotificacoesRoute: typeof ConfiguracoesNotificacoesRoute
  ConfiguracoesOkrRoute: typeof ConfiguracoesOkrRoute
  ConfiguracoesPopupDiarioRoute: typeof ConfiguracoesPopupDiarioRoute
  ConfiguracoesStatusUsuariosRoute: typeof ConfiguracoesStatusUsuariosRoute
  ConfiguracoesUsuariosRoute: typeof ConfiguracoesUsuariosRoute
  ConfiguracoesZapiRoute: typeof ConfiguracoesZapiRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesAssistenteIaRoute: ConfiguracoesAssistenteIaRoute,
  ConfiguracoesAuditoriaRoute: ConfiguracoesAuditoriaRoute,
  ConfiguracoesAutomacaoSemComunicacaoRoute:
    ConfiguracoesAutomacaoSemComunicacaoRoute,
  ConfiguracoesCentralAtendimentoRoute: ConfiguracoesCentralAtendimentoRoute,
  ConfiguracoesEncaminhamentoRoute: ConfiguracoesEncaminhamentoRoute,
  ConfiguracoesEstoqueRoute: ConfiguracoesEstoqueRoute,
  ConfiguracoesFluxoAtendimentoRoute: ConfiguracoesFluxoAtendimentoRoute,
  ConfiguracoesNotificacoesRoute: ConfiguracoesNotificacoesRoute,
  ConfiguracoesOkrRoute: ConfiguracoesOkrRoute,
  ConfiguracoesPopupDiarioRoute: ConfiguracoesPopupDiarioRoute,
  ConfiguracoesStatusUsuariosRoute: ConfiguracoesStatusUsuariosRoute,
  ConfiguracoesUsuariosRoute: ConfiguracoesUsuariosRoute,
  ConfiguracoesZapiRoute: ConfiguracoesZapiRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentosRoute: AtendimentosRoute,
  CentralRoute: CentralRoute,
  ChatOperadoresRoute: ChatOperadoresRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ContatosRoute: ContatosRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  EmpresasRoute: EmpresasRoute,
  EstoqueRoute: EstoqueRoute,
  OkrRoute: OkrRoute,
  PainelTvRoute: PainelTvRoute,
  RelatoriosRoute: RelatoriosRoute,
  TratativasRoute: TratativasRoute,
  AtendimentosTarefasRoute: AtendimentosTarefasRoute,
  HooksRefreshTrackingRoute: HooksRefreshTrackingRoute,
  ApiPublicAutoRouteAguardandoRoute: ApiPublicAutoRouteAguardandoRoute,
  ApiPublicChatIdleScannerRoute: ApiPublicChatIdleScannerRoute,
  ApiPublicCrmDailyRoute: ApiPublicCrmDailyRoute,
  ApiPublicEmailPollRoute: ApiPublicEmailPollRoute,
  ApiPublicZapiWebhookChannelIdRoute: ApiPublicZapiWebhookChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
